# Command to start on workspace startup (optional)
tasks:
  - before: nvm install 16
    init: npm install;
    command: run start;
# Ports to expose on workspace startup (optional)
ports:
  - port: 3000
    onOpen: open-preview
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
